#ifndef GAME_SERVER_GAMEMODES_SHEEP_WEAPON_H
#define GAME_SERVER_GAMEMODES_SHEEP_WEAPON_H

#include <game/generated/protocol.h>

enum EWeaponType {
	// WEAPON_NONE = -1,
	WEAPON_TELEKINESIS = NUM_WEAPONS,
	WEAPON_HEARTGUN,
	WEAPON_LIGHTSABER,
	WEAPON_PORTALGUN,
	NUM_WEAPON_TYPES
};

#endif